# Generated by Django 6.0.7 on 2026-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complimentary_access',
            field=models.BooleanField(default=False, help_text="Accesso omaggio: l'utente puo' usare il sistema senza abbonamento Stripe"),
        ),
    ]
