# Generated by Django 6.0.7 on 2026-07-18 07:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BoundaryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=14)),
                ('metric_crs', models.CharField(max_length=16)),
                ('source', models.CharField(choices=[('draw', 'Disegno mappa'), ('upload', 'Caricamento file')], default='draw', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='fields.field')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['owner', '-created_at'], name='fields_fiel_owner_i_0cca78_idx'),
        ),
        migrations.AddConstraint(
            model_name='boundaryversion',
            constraint=models.UniqueConstraint(fields=('field', 'version'), name='fields_unique_boundary_version'),
        ),
        migrations.AddConstraint(
            model_name='boundaryversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='fields_boundary_version_positive'),
        ),
    ]
