# Generated by Django 6.0.7 on 2026-07-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0002_analysisjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
