# Generated by Django 6.0.7 on 2026-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='crop',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
