# Generated by Django 6.0.7 on 2026-08-04 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_field_crop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='delete_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='delete_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervention',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('delete', 'Cestino'), ('restore', 'Ripristino'), ('purge', 'Eliminazione definitiva')], max_length=16)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='fields_audi_entity__a843dc_idx')],
            },
        ),
        # Fase 2: guard aggiornato (bypass GUC per il purge job), trigger
        # audit/demo/boundary, vincoli di integrita' (CHECK + FK owner composita).
        # La funzione guard e' creata solo se assente: su pcc esiste dal 2026-07-31
        # (owner postgres) e viene aggiornata manualmente con lo stesso codice.
        migrations.RunSQL(
            sql="""
CREATE SCHEMA IF NOT EXISTS verdimetria_guard;

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'verdimetria_guard'
      AND p.proname = 'block_customer_destructive_dml'
  ) THEN
    CREATE FUNCTION verdimetria_guard.block_customer_destructive_dml()
    RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog' AS $fn$
    BEGIN
      IF session_user <> 'postgres'
         AND current_setting('verdimetria.allow_purge', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'Verdimetria guard: % blocked on %.% (purge richiede verdimetria.allow_purge=on)',
          TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME USING ERRCODE = '42501';
      END IF;
      IF TG_OP = 'TRUNCATE' THEN RETURN NULL; END IF;
      RETURN OLD;
    END;
    $fn$;
  END IF;
END
$guard$;

-- Trigger delete/truncate sulle 5 tabelle cliente (idempotenti).
DROP TRIGGER IF EXISTS verdimetria_guard_delete ON public.accounts_user;
CREATE TRIGGER verdimetria_guard_delete BEFORE DELETE ON public.accounts_user
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_truncate ON public.accounts_user;
CREATE TRIGGER verdimetria_guard_truncate BEFORE TRUNCATE ON public.accounts_user
  FOR EACH STATEMENT EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_delete ON public.fields_field;
CREATE TRIGGER verdimetria_guard_delete BEFORE DELETE ON public.fields_field
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_truncate ON public.fields_field;
CREATE TRIGGER verdimetria_guard_truncate BEFORE TRUNCATE ON public.fields_field
  FOR EACH STATEMENT EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_delete ON public.fields_boundaryversion;
CREATE TRIGGER verdimetria_guard_delete BEFORE DELETE ON public.fields_boundaryversion
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_truncate ON public.fields_boundaryversion;
CREATE TRIGGER verdimetria_guard_truncate BEFORE TRUNCATE ON public.fields_boundaryversion
  FOR EACH STATEMENT EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_delete ON public.fields_analysisjob;
CREATE TRIGGER verdimetria_guard_delete BEFORE DELETE ON public.fields_analysisjob
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_truncate ON public.fields_analysisjob;
CREATE TRIGGER verdimetria_guard_truncate BEFORE TRUNCATE ON public.fields_analysisjob
  FOR EACH STATEMENT EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_delete ON public.fields_intervention;
CREATE TRIGGER verdimetria_guard_delete BEFORE DELETE ON public.fields_intervention
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();
DROP TRIGGER IF EXISTS verdimetria_guard_truncate ON public.fields_intervention;
CREATE TRIGGER verdimetria_guard_truncate BEFORE TRUNCATE ON public.fields_intervention
  FOR EACH STATEMENT EXECUTE FUNCTION verdimetria_guard.block_customer_destructive_dml();

-- Audit append-only: nessun UPDATE/DELETE, per nessuno.
CREATE OR REPLACE FUNCTION verdimetria_guard.block_audit_mutation()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog' AS $fn$
BEGIN
  RAISE EXCEPTION 'Verdimetria guard: audit append-only, % blocked', TG_OP
    USING ERRCODE = '42501';
END;
$fn$;
DROP TRIGGER IF EXISTS verdimetria_guard_audit_immutable ON public.fields_auditentry;
CREATE TRIGGER verdimetria_guard_audit_immutable
  BEFORE UPDATE OR DELETE ON public.fields_auditentry
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_audit_mutation();

-- Campo demo: mai cestinabile dai flussi ordinari.
CREATE OR REPLACE FUNCTION verdimetria_guard.block_demo_soft_delete()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog' AS $fn$
BEGIN
  IF session_user <> 'postgres' THEN
    RAISE EXCEPTION 'Verdimetria guard: soft delete del campo demo bloccato'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$fn$;
DROP TRIGGER IF EXISTS verdimetria_guard_demo_delete ON public.fields_field;
CREATE TRIGGER verdimetria_guard_demo_delete BEFORE UPDATE ON public.fields_field
  FOR EACH ROW
  WHEN (OLD.is_demo AND OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL)
  EXECUTE FUNCTION verdimetria_guard.block_demo_soft_delete();

-- Versioni di confine immutabili.
CREATE OR REPLACE FUNCTION verdimetria_guard.block_boundary_mutation()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog' AS $fn$
BEGIN
  IF session_user <> 'postgres' THEN
    RAISE EXCEPTION 'Verdimetria guard: boundary version immutabile'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$fn$;
DROP TRIGGER IF EXISTS verdimetria_guard_boundary_update ON public.fields_boundaryversion;
CREATE TRIGGER verdimetria_guard_boundary_update
  BEFORE UPDATE ON public.fields_boundaryversion
  FOR EACH ROW EXECUTE FUNCTION verdimetria_guard.block_boundary_mutation();

-- Vincoli di integrita' (NOT VALID + VALIDATE per non bloccare la produzione).
ALTER TABLE public.fields_field
  ADD CONSTRAINT fields_field_id_owner_uniq UNIQUE (id, owner_id);

ALTER TABLE public.fields_analysisjob
  ADD CONSTRAINT fields_analysisjob_status_check
  CHECK (status IN ('pending', 'running', 'completed', 'failed')) NOT VALID;
ALTER TABLE public.fields_analysisjob
  VALIDATE CONSTRAINT fields_analysisjob_status_check;

ALTER TABLE public.fields_analysisjob
  ADD CONSTRAINT fields_analysisjob_timestamps_check
  CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
  NOT VALID;
ALTER TABLE public.fields_analysisjob
  VALIDATE CONSTRAINT fields_analysisjob_timestamps_check;

ALTER TABLE public.fields_boundaryversion
  ADD CONSTRAINT fields_boundaryversion_area_positive
  CHECK (area_hectares > 0) NOT VALID;
ALTER TABLE public.fields_boundaryversion
  VALIDATE CONSTRAINT fields_boundaryversion_area_positive;

ALTER TABLE public.fields_boundaryversion
  ADD CONSTRAINT fields_boundaryversion_geometry_valid
  CHECK (geometry IS NOT NULL AND ST_IsValid(geometry) AND ST_SRID(geometry) = 4326)
  NOT VALID;
ALTER TABLE public.fields_boundaryversion
  VALIDATE CONSTRAINT fields_boundaryversion_geometry_valid;

-- FK composita: job e interventi devono avere lo stesso owner del campo.
DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname FROM pg_constraint
  WHERE conrelid = 'public.fields_analysisjob'::regclass AND contype = 'f'
    AND pg_get_constraintdef(oid) LIKE '%(field_id)%';
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.fields_analysisjob DROP CONSTRAINT %I', cname);
  END IF;
END $$;
ALTER TABLE public.fields_analysisjob
  ADD CONSTRAINT fields_analysisjob_field_owner_fk
  FOREIGN KEY (field_id, owner_id)
  REFERENCES public.fields_field (id, owner_id)
  ON DELETE CASCADE NOT VALID;
ALTER TABLE public.fields_analysisjob
  VALIDATE CONSTRAINT fields_analysisjob_field_owner_fk;

DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname FROM pg_constraint
  WHERE conrelid = 'public.fields_intervention'::regclass AND contype = 'f'
    AND pg_get_constraintdef(oid) LIKE '%(field_id)%';
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.fields_intervention DROP CONSTRAINT %I', cname);
  END IF;
END $$;
ALTER TABLE public.fields_intervention
  ADD CONSTRAINT fields_intervention_field_owner_fk
  FOREIGN KEY (field_id, owner_id)
  REFERENCES public.fields_field (id, owner_id)
  ON DELETE CASCADE NOT VALID;
ALTER TABLE public.fields_intervention
  VALIDATE CONSTRAINT fields_intervention_field_owner_fk;
""",
            # Reverse manuale documentato nel piano sicurezza: drop dei constraint
            # e ricreazione della FK semplice; i trigger guard restano (Fase 0).
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
