# Generated by Django 6.0.7 on 2026-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_field_delete_reason_field_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='ai_cost_eur',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='ai_tokens_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='ai_tokens_out',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
